export const ACCOUNT_AUTH_STATUS_CHANGED = "ACCOUNT_AUTH_STATUS_CHANGED";
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAILED = 'ACCOUNT_REGISTER_FAILED';
export const ACCOUNT_LOGIN_SUCCESS = "ACCOUNT_LOGIN_SUCCESS";
export const ACCOUNT_LOGIN_FAILED = "ACCOUNT_LOGIN_FAILED";
export const ACCOUNT_EDIT_USER = "ACCOUNT_EDIT_USER";
export const ACCOUNT_AVATAR_UPLOAD = "ACCOUNT_AVATAR_UPLOAD";
